### PR TITLE
deps: upgrade koa-onerror

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

Ref eggjs/egg#124

### CODE REVIEW

**Comment by dead-horse** [comment]
CI 挂了？

**Comment by popomore** [comment]
koa-onerror 有点问题

**Comment by popomore** [comment]
https://github.com/koajs/onerror/pull/16

**Comment by dead-horse** [comment]
+1

**Comment by dead-horse** [comment]
这个可以发 1.0.0 了吧？

**Comment by popomore** [comment]
可以了

**Pull request merged**
