### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by atian25**
close https://github.com/eggjs/egg/issues/1297

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

close https://github.com/eggjs/egg/issues/1297

### CODE REVIEW

**Comment by popomore** [comment]
Win 挂了？

**Comment by iyuq** [comment]
感觉是不是拼错了的应该保留，增加个正确的

**Comment by atian25** [comment]
只是文档错误

发自我的 iPhone

**Comment by fengmk2** [comment]
ci 挂了

**Pull request merged**
